language: java
env:
  global:
    - CATALINA_PID=/tmp/tomcat.pid
    - CATALINA_OUT=/tmp/tomcat.log
    - CATALINA_OPTS="-XX:MaxPermSize=256M -DUAA_PROFILE=local"
  matrix:
    - SPRING_PROFILES=
    - SPRING_PROFILES=default,saml
before_install:
  - git pull --unshallow
  - wget -O tomcat.tar.gz http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.52/bin/apache-tomcat-7.0.52.tar.gz
  - unset GEM_PATH # for compatibility with the maven-sass-plugin
install:
  - $TRAVIS_BUILD_DIR/.apply_spring_profiles_to_login_yaml.sh $SPRING_PROFILES
  - cat login-server/src/main/resources/login.yml
  - mvn -U clean --quiet -DskipTests=true
  - mvn -U install --quiet -DskipTests=true
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p target/tomcat
  - tar zxf tomcat.tar.gz -C target/tomcat --strip-components 1
  - export WEBAPPS_DIR=$TRAVIS_BUILD_DIR/target/tomcat/webapps
  - rm -rf $WEBAPPS_DIR/*
  - mvn dependency:copy -Dartifact=org.cloudfoundry.identity:cloudfoundry-identity-uaa:1.6.3-SNAPSHOT:war -DoutputDirectory=$WEBAPPS_DIR
  - mv $WEBAPPS_DIR/cloudfoundry-identity-uaa-*.war $WEBAPPS_DIR/uaa.war
  - mvn dependency:copy -Dartifact=org.cloudfoundry.identity:cloudfoundry-identity-app:1.6.3-SNAPSHOT:war -DoutputDirectory=$WEBAPPS_DIR
  - mv $WEBAPPS_DIR/cloudfoundry-identity-app-*.war $WEBAPPS_DIR/app.war
  - mvn dependency:copy -Dartifact=org.cloudfoundry.identity:cloudfoundry-identity-api:1.6.3-SNAPSHOT:war -DoutputDirectory=$WEBAPPS_DIR
  - mv $WEBAPPS_DIR/cloudfoundry-identity-api-*.war $WEBAPPS_DIR/api.war
  - mvn -Dwar.exploded.dir=$WEBAPPS_DIR/login -pl login-server war:exploded
script:
  - ./.run-script.sh start
  - mvn -Dtest=org.cloudfoundry.identity.uaa.login.integration.*Tests -DfailIfNoTests=false test --quiet
  - cd login-server-integration-tests
  - mvn -Dspring.profiles.active=${SPRING_PROFILES} verify --quiet
  - cd $TRAVIS_BUILD_DIR
  - ./.run-script.sh stop
  - mvn -Dspring.profiles.active=$TESTENV test --quiet
after_success:
  - mvn -pl login-server clean cobertura:cobertura coveralls:cobertura
after_failure:
  - cat $CATALINA_OUT
after_script:
  - rm -rf tomcat
  - rm -f tomcat.tar.gz
